name: Install Yarn dependencies
description: Installs the workspace's yarn dependencies and caches them
inputs:
  version:
    description: The version of the project to install dependencies for
    required: true

runs:
  using: composite
  steps:
    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.2
      with:
        toolchain: ${{ inputs.version }}

    - name: Use Nargo
      run: nargo --version
      shell: bash
