name: PR - with-foundry
on:
  pull_request:
    paths:
      - 'with-foundry/**'

jobs:
  test-with-foundry:
    defaults:
      run:
        working-directory: with-foundry

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: 0.11.0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Generate verifier contract
        run: |
          nargo codegen-verifier
        working-directory: with-foundry/circuits

      - name: Generate proof
        run: |
          nargo prove
        working-directory: with-foundry/circuits

      - name: Test with Foundry
        run: |
          forge test --optimize --optimizer-runs 5000 --evm-version london
